baseURL = 'https://www.sh05.dev'
defaultContentLanguage = 'ja'
title = '/var/logs/lifed/error_log'
theme = 'cupper-hugo-theme'
summarylength = 100
HasCJKLanguage = true
publishDir = "docs"
paginate = 10
googleAnalytics = "UA-212963708-1"

[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'

[menu] # メニューバーの設定
  [[menu.nav]]
    name = "Home"   # 表示される名称
    url = "/"    # 参照するアドレス
    weight = 1
  [[menu.nav]]
    name = "Blog"   # 表示される名称
    url = "/posts/"    # 参照するアドレス
    weight = 3
  [[menu.nav]]
    name = "About"   # 表示される名称
    url = "/about/"    # 参照するアドレス
    weight = 100
  [[menu.nav]]
    name = "Categories"   # 表示される名称
    url = "/categories/"    # 参照するアドレス
    weight = 12
  [[menu.nav]]
    name = "Tags"   # 表示される名称
    url = "/tags/"    # 参照するアドレス
    weight = 11
  [[menu.nav]]
    name = "Series"   # 表示される名称
    url = "/series/"    # 参照するアドレス
    weight = 13
  [[menu.nav]]
    name = "Logs"   # 表示される名称
    url = "/logs/"    # 参照するアドレス
    weight = 4
  [[menu.nav]]
    name = "RSS"   # 表示される名称
    url = "/index.xml"    # 参照するアドレス
    weight = 99

[params]
  description = 'ぼくの人生のエラーログ'
  author = 'Shogo Nakamoto'
  GitHubUser = 'sh05'
  ListOfFoo = ['foo1', 'foo2']
  SidebarRecentLimit = 5
  hideHeaderLinks = true
  search = true
  readingTime = true
  wordCount = true
  socialShare = true
  customCSS = ["/css/mystyle.css", "/css/styles.css"]

[permalinks]
  posts = '/:year/:month/:day/:title/'

enableEmoji = true
hasCJKLanguage = true
timeZone = 'Asia/Tokyo'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true

    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = false
        title = true


    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false

  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'monokai'
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

